=== MohitP197-zz/XML-basic-website/catalog_16034897.dtd
<!--This document stores the DTD information for the the XML file catalog_16034897.xml-->
	<!-- 
		Author: Mohit Paudel
		Group: C5
		Londonmet ID: 16034897 
	-->

	<!ELEMENT root (Electronic_Store,Items)>

	<!ELEMENT Electronic_Store (Store_Name,Address,Telephone_Number,Website,Logo)>
	<!ELEMENT Store_Name (#PCDATA)>
	<!ELEMENT Address (#PCDATA)>
	<!ELEMENT Telephone_Number (#PCDATA)>
	<!ELEMENT Website (#PCDATA)>
	<!ELEMENT Logo (#PCDATA)>

	<!ELEMENT Items (CPUs,Monitor,Mouses,Keyboards,Hard_Disks,Speakers)>
	<!ELEMENT CPUs (CPU+)>
	
	<!ELEMENT CPU (Name,Item_Number,Description,Quantity,Processor_Speed,Item_Dimensions,Processor_Count,Price_Dollar,Price_Pound,Delivery?)>

	<!ELEMENT Name (#PCDATA)>
	<!ELEMENT Item_Number (#PCDATA)>
	<!ELEMENT Description (#PCDATA)>
	<!ELEMENT Quantity (#PCDATA)>
	<!ELEMENT Processor_Speed (#PCDATA)>
	<!ELEMENT Item_Dimensions (#PCDATA)>
	<!ELEMENT Processor_Count (#PCDATA)>
	<!ELEMENT Price_Dollar (#PCDATA)>
	<!ELEMENT Price_Pound (#PCDATA)>
	<!ELEMENT Delivery (#PCDATA)>
	
	<!ELEMENT Monitor (CRT+,LED+,LCD+)>

	<!ELEMENT CRT (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?,Information)>
	

	<!ELEMENT Information (Manufacturer,Resolution,Dimension,Color)>
	<!ELEMENT Manufacturer (#PCDATA)>
	<!ELEMENT Resolution (#PCDATA)>
	<!ELEMENT Dimension (#PCDATA)>
	<!ELEMENT Color (#PCDATA)>
	
	<!ELEMENT LED (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?,Information)>

	<!ELEMENT LCD (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?,Information)>
	
	<!ELEMENT Mouses (Mouse+)>
	<!ELEMENT Mouse (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?)>
	 

	<!ELEMENT Keyboards (Keyboard+)>
	<!ELEMENT Keyboard (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?)>
	

	<!ELEMENT Hard_Disks (Hard_Disk+)>
	<!ELEMENT Hard_Disk (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?)>


	<!ELEMENT Speakers (Speaker+)>
	<!ELEMENT Speaker (Name,Item_Number,Description,Quantity,Price_Dollar,Price_Pound,Delivery?)>

	<!ATTLIST CRT Speaker  #IMPLIED>
	<!ATTLIST LED Speaker  #IMPLIED>
	<!ATTLIST LCD Speaker  #IMPLIED>
	<!ATTLIST CPU ref IDREFS #REQUIRED>
	<!ATTLIST CRT id ID #REQUIRED>
	<!ATTLIST LED id ID #REQUIRED>
	<!ATTLIST LCD id ID #REQUIRED>
	<!ATTLIST Keyboard id ID #REQUIRED>
	<!ATTLIST Hard_Disk id ID #REQUIRED>
	<!ATTLIST Speaker id ID #REQUIRED>

=== MohitP197-zz/XML-basic-website/catalog_16034897.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--This document is the main XML file, which stores the information of for the SK electronic store -->
<!--
	Author: Mohit Paudel 
	Group: C5
	Londonmet ID: 16034897
-->
<?xml-stylesheet type = "text/css" href="catalog_16034897.css"?>
<!DOCTYPE root SYSTEM "catalog_16034897.dtd">
<root>

	<Electronic_Store>
		<Store_Name>SK Electronic Store</Store_Name>
		<Address>Banasthali, Kathmandu</Address>
		<Telephone_Number>014242121, 9841417894</Telephone_Number>
		<Website>www.skelectronicstore.com</Website>
		<Logo></Logo>
	</Electronic_Store>

	<Items>
		
		<CPUs>
			
			<CPU id="c401" ref="c501 c601 c701 c801">
				<Name>Intel® Core™ i7-6950X Processor Extreme Edition </Name>
				<Item_Number>1</Item_Number>
				<Description>

					<![CDATA[With the Intel Core i7 69xx/68xx processor family, you can run several CPU–heavy programs simultaneously without sacrificing performance. A 35% improvement in multi-threaded 3D rendering speed versus the previous generation and up to 2x better multi-threaded 3D-rendering performance versus our latest 4 core processor1 means you can spend more time creating and less time waiting. Experience fast video encode, image rendering, audio production, and real-time previews that you can check out on a bank of monitors at a great resolution. Lags will not be tolerated: Play. Broadcast. Record. Win. In 4K. Get gaming superpowers with the Intel Core i7 processor Extreme Edition, which features Intel Turbo Boost Max Technology 3.03 for more than 15% better single-threaded performance4, blistering 2400MHz memory, fully- loaded 25 MB of Smart Cache, and up to 4 discrete graphics cards working together for your most demanding games. The Intel Core i7 69xx/68xx processor family is unlocked to provide additional headroom. New features include the ability to overclock each core individually, AVX ratio controls for more stability, and VccU voltage control for extreme scenarios. Combined with tools like Intel's Extreme Tuning Utility (Intel XTU) and Extreme Memory Profile (Intel XMP), you have a powerful kit for maximizing performance.]]> 

				</Description>
				<Quantity>1</Quantity>
				<Processor_Speed>3.50 GHz</Processor_Speed>
				<Item_Dimensions>1.61 x 4.56 x 3.93 in</Item_Dimensions>
				<Processor_Count>10</Processor_Count>
				<Price_Dollar>$1743</Price_Dollar>
				<Price_Pound>&#163;1654</Price_Pound>
				<Delivery>Free Delivery</Delivery>
			</CPU>

			<CPU id="c402" ref="c502 c602 c702 c802">
				<Name>AMD Ryzen Threadripper 1950X Processor</Name>
				<Item_Number>2</Item_Number>
				<Description>

					<![CDATA[For casual gaming, we would say a $200 (about £154 AU$254) processor is good enough, and $300 (about £231, AU$381) if you’re looking for something futureproofed for at least a few years. With this mind, paying $1244 for the Rzyen Threadripper 1950X might be mind boggling to most users.This is exactly why AMD is marketing this chip to its die-hard fans, the ultimate mega-taskers and gamers who also want to play, record, stream and produce video – all at the same time.Even if you’re not that person, AMD arguably makes a better case for its $12K processor than the Intel Core i9-7900X. On paper, the Threadripper has six more cores and 12 more threads than the Core X part, though, Intel has the upper hand with a greater range of 3.3GHz base/4.3GHz boost clock speeds and a lower 140-watt thermal design power. If you’ve never handled server-grade components before, Threadripper will be an eye opener for you. The processor is physically twice the width of most consumer market CPUs. What’s more, instead of plopping a chip onto the motherboard, Threadripper CPUs come attached to a holder you slide into place.Those with liquid-cooling solutions also might find it especially unnerving to see the corners of their processor uncovered and bare – rest easy, the processor dies are positioned in the center of the chip.Once you get over the new physical nuances of Threadripper, there are also new software profiles to get your head wrapped around. Out of the box, the 1950X and all Threadripper parts thus far are configured to run in either a Creative or Game Mode. Without getting too deep into technical aspects, users can for the most part expect premiere, video encoding and multi-tasking to operate more smoothly in Creative Mode. Meanwhile, Game Mode has the CPU turn off half its cores and return to a more traditional memory access protocol, which helps it deliver slightly higher frame rates while gaming.]]> 


				</Description>
				<Quantity>3</Quantity>
				<Processor_Speed>4 GHz</Processor_Speed>
				<Item_Dimensions>2.2 x 3.1 x 0.3 in</Item_Dimensions>
				<Processor_Count>16</Processor_Count>
				<Price_Dollar>$1244</Price_Dollar>
				<Price_Pound>&#163;1156</Price_Pound>
				<Delivery>Express Delivery</Delivery>
			</CPU>

			<CPU id="c403" ref="c503 c603 c703 c803">
				<Name>Intel® Core™ i9-7980XE Processor</Name>
				<Item_Number>3</Item_Number>
				<Description>

					<![CDATA[In short, the Intel Core i9-7980XE is nothing if not monstrous with 18 cores and 36 threads squeezed into Intel’s tiny Skylake-X 14nm architecture. The processor also features 24.75 MB of Smart Cache, support for up to 44 PCIe 3.0 lanes, quad channel memory, and a 165W TDP. More impressively, it also features a base clock frequency of 2.60 GHz that turbos up to 3.4 GHz across all 18 cores when under full load. This processor truly stretches the limits of Intel’s Skylake X architecture and amazingly it all fits in a package that’s more or less half the width of Ryzen Threadripper. The Intel Core i9-7980XE demolished all of our benchmarks, scoring an incredible 3,331 points in CineBench’s multi-threaded benchmark (100 points less than an overclocked Threadripper 1950X), and a staggering 184 points in the single-threaded operation.To put that into perspective, a Core i5-7600K, arguably the go-to processor for strong single core performance – which is crucial for gaming – scores five fewer points at 179. This is due to two reasons. Firstly, the strength of Intel’s Skylake-X Core architecture, and secondly, the introduction of Turbo 3.0, which introduces the ability to overclock anywhere from one-to-four of the chip’s best cores up to 4.2GHz. It does all of this whilst remaining cool as well. By default, Intel does not ship any of its X-series processors with included coolers. The theory being that if you’re willing to invest two grand on a part this expensive, you’ll likely use an aftermarket cooler, to keep your lavish investment well chilled.That said, under our NZXT Kraken X62 280mm AIO cooler, it was rare for it to peak past 55 degrees under load. Even whilst overclocked, we only ever saw it reach around 87 degrees at maximum.Power draw is also fairly concrete, pulling a total of 258W under a single instance of Prime95’s burn test from the wall socket. That’s 13 fewer watts than AMD’s Threadripper 1950X.It’s only after you start messing around with those multipliers and voltages that the Core i9-7980XE’s true potential is unlocked. Generally speaking, though, overclocking X299 parts has been troublesome because of two problems. Firstly, VRMs thermally-throttling under Prime95 loads, forces processors to declock. Secondly, Intel still doesn’t solder its CPUs directly to the Integrated Heat Spreader (IHS) and instead uses inadequate thermal paste to do the job. Overall, it’s been challenging to get the most out of these chips.]]> 

				</Description>
				<Quantity>2</Quantity>
				<Processor_Speed>4.3 GHz</Processor_Speed>
				<Item_Dimensions>1.53 x 3.94 x 1.57 in</Item_Dimensions>
				<Processor_Count>18</Processor_Count>
				<Price_Dollar>$1999</Price_Dollar>
				<Price_Pound>&#163;1675</Price_Pound>
				<Delivery>Express Delivery</Delivery>
			</CPU>

			
		</CPUs>
		


		<Monitor>
			
			<CRT id="c501">
				
				<Name>Dell P793</Name>
				<Item_Number>10</Item_Number>
				<Description>

					<![CDATA[Dell's 17-inch monitor is a solid, inexpensive entry into the CRT world. It delivers a 0.27-millimeter dot pitch and a maximum 1,280 x 1,024 resolution, providing amply sharp and clear images for everyday tasks such as word processing, spreadsheets, Web surfing, and games. The viewable screen size is 16 inches, so you don't have to strain your eyes whenever you use your computer. The screen has an antiglare and antistatic coating to increase visibility. Compatible with PC systems, the monitor is completely plug and play, meaning it's ready to use right out of the box. Box consists of Monitor, base, power cable, signal cable, instructions, warranty information.]]>
						
				</Description>
				
				<Quantity>2</Quantity>
				<Price_Dollar>$201.50</Price_Dollar>
				<Price_Pound>&#163;150</Price_Pound>
				<Delivery>Express Delivery</Delivery>

				<Information>
					<Manufacturer>Dell</Manufacturer>
					<Resolution>1280 x 1024</Resolution>
					<Dimension>17"</Dimension>
					<Color>Black</Color>
				</Information>

			</CRT>

			<LED id="c502">
				
				<Name>Acer Predator X34</Name>
				<Item_Number>11</Item_Number>
				<Description>
